server:
  port: 8080
eureka:
  instance:
      hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms1
          uri: lb://ms1
          predicates:
            - Path=/price/**
        - id: ms2
          uri: lb://ms2
          predicates:
            - Path=/group-discount/**
        - id: ms3
          uri: lb://ms3
          predicates:
            - Path=/clients/**
        - id: ms4
          uri: lb://ms4
          predicates:
            - Path=/specialdays-discount/**
        - id: ms5
          uri: lb://ms5
          predicates:
            - Path=/reservations/**
            - Path=/email/**