apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3
  labels:
    app: ms3-deployment
spec:
  selector:
    matchLabels:
      app: ms3-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms3-deployment
    spec:
      containers:
        - name: ms3
          image: javiersalasm/ms3
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_MS3
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_MS3
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_MS3
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_MS3
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_MS3