apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms6
  labels:
    app: ms6-deployment
spec:
  selector:
    matchLabels:
      app: ms6-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms6-deployment
    spec:
      containers:
        - name: ms6
          image: javiersalasm/ms6
          ports:
            - containerPort: 8095
          env:
            - name: SERVER_PORT
              value: "0"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"