apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_MS1: cG9zdGdyZXM=
  DB_PASSWORD_MS1: MTIzNA==
  DB_USER_MS2: cG9zdGdyZXM=
  DB_PASSWORD_MS2: MTIzNA==
  DB_USER_MS3: cG9zdGdyZXM=
  DB_PASSWORD_MS3: MTIzNA==
  DB_USER_MS4: cG9zdGdyZXM=
  DB_PASSWORD_MS4: MTIzNA==
  DB_USER_MS5: cG9zdGdyZXM=
  DB_PASSWORD_MS5: MTIzNA==